version: '3.8'
services:
  course-service:
    build: ./services/course-service
    ports:
      - "8001:8000"

  schedule-service:
    build: ./services/schedule-service
    ports:
      - "8002:8000"

  enrollment-service:
    build: ./services/enrollment-service
    ports:
      - "8003:8000"
    depends_on:
      - course-service
      - schedule-service

